const CREATE_PRODUCT = "CREATE_PRODUCT";
const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
const GET_CATEGORY = "GET_CATEGORY";
const GET_ALL_CITIES = "GET_ALL_CITIES";
const LOADING = "LOADING";
const READY = "READY";
const COMMERCE_LOGIN = "COMMERCE_LOGIN";
const GET_COMMERCE_BY_ID = "GET_COMMERCE_BY_ID";
const UPDATE_COMMERCE = "UPDATE_COMMERCE";
const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

module.exports = {
  CREATE_PRODUCT,
  GET_PRODUCT_BY_NAME,
  GET_CATEGORY,
  GET_ALL_CITIES,
  LOADING,
  READY,
  COMMERCE_LOGIN,
  GET_COMMERCE_BY_ID,
  UPDATE_COMMERCE,
  GET_PRODUCT_BY_CATEGORY,
  GET_ALL_PRODUCTS
};
