const CREATE_PRODUCT = "CREATE_PRODUCT";

// Filtros
const FILTER_PRICE = "FILTER_PRICE";
const FILTER_CONDITION = "FILTER_CONDITION";

module.exports = {
  CREATE_PRODUCT,
  FILTER_PRICE,
  FILTER_CONDITION,
};
